baseurl = "https://woneill.com/"
title = "woneill.com"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "William O'Neill"
googleAnalytics = "UA-124203524-1"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "William O'Neill"
    profile = "https://woneill.com/"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "William O'Neill"
    description = "The Path of a Reformed BOFH"
    github = "https://github.com/woneill"
    linkedin = "https://linkedin.com/in/williamoneill/"
    twitter = "https://twitter.com/woneill"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = false
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
